# -*- coding: utf-8 -*-
"""Global _Music_Streaming_Listener_Preferences.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GColVfyEw7HfJ3b0gvo0xNp8TuDb_07s
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Global_Music_Streaming_Listener_Preferences.csv")

df.head()

df.tail()

df.describe()

df.dtypes

"""key questions to explore:
1. What are the most popular music streaming platform?
2. How does age impact music preferences?
3. What are the most streamed genres and artists?
4. How does free vs premium users differ in streaming behavior?
5. What time of the day do users stream music the most?
6. Are there any regional trends in music streaming preferences?



"""

df.isnull().sum()

df.duplicated().sum()

df.info()

list_cols_num = ("Age","Minutes Streamed Per Day","Number of Songs Liked","Discover Weekly Engagement (%)","Repeat Song Rate (%)")
for i in list_cols_num:
  sns.boxplot(data=df,x=i)
  plt.show()

df.columns

list_numericals_cat = ("Country","Streaming Platform","Top Genre","Most Played Artist", "Subscription Type","Listening Time (Morning/Afternoon/Night)")
for i in list_numericals_cat:
  print(df[i].value_counts())

df_sp= df["Streaming Platform"].value_counts()

df_sp

df_sp.values

df_sp.index

plt.figure(figsize=(6,6))
plt.bar(df_sp.index,df_sp.values)
plt.xlabel("Streaming Platform")
plt.ylabel("Frequency")
plt.title("distribution of Streaming Platform")
plt.show()

#Amazon is the most prefered streaming platform
#Apple Music is the least prefered streaming platform

#age impact music preferences

def age_func(x):
  if x<18:
    return "<18"
  elif  x>= 18 and x <= 30:
    return "18-30"
  elif x >= 31 and x <= 45:
    return "31-45"
  elif x>= 45 and x <= 60:
    return "46-60"
  else:
    pass

df["Age_Group"]= df["Age"].apply(age_func)

df.head()

age_music= pd.crosstab(df["Age_Group"],df["Top Genre"])
fig, ax= plt.subplots(figsize=(10,6))
age_music.plot(kind='bar', ax = ax)
ax.set_xlabel("Age Group")
ax.set_ylabel("Frequency")
ax.set_title("Impact of age on music preferences")

plt.show()

#Age impact music preferences

age_music = pd.crosstab(df["Age_Group"],df["Top Genre"], normalize = 'index')* 100
fig, ax= plt.subplots(figsize=(10,6))
age_music.plot(kind='bar', ax = ax, stacked = True)
ax.set_xlabel("Age Group")
ax.set_ylabel("percentage")
ax.legend(title="Music Genre")
ax.set_title("Impact of age on music preferences")

plt.show()

#3. What are the most streamed genres and artists?

df.groupby("Most Played Artist")["Minutes Streamed Per Day"].sum().sort_values(ascending=False).head()

df.groupby("Top Genre")["Minutes Streamed Per Day"].sum().sort_values(ascending=False).head()

#Most streamed Artist Bunny
#Most streamed Genre Rock

df_genre = df["Top Genre"].value_counts()
plt.figure(figsize=(10,6))
plt.bar(df_genre.index, df_genre.values)
plt.xlabel("Genre")
plt.ylabel("Frequency")
plt.title("Most Streamed Genres")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

df_artist = df["Most Played Artist"].value_counts()
plt.figure(figsize=(10,6))
plt.bar(df_artist.index, df_artist.values)
plt.xlabel("Artist")
plt.ylabel("Frequency")
plt.title("Most Streamed Artists")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

#4. How does free vs premium users differ in streaming behavior?



subscription_behavior = df.groupby('Subscription Type')[[
    'Minutes Streamed Per Day',
    'Number of Songs Liked',
    'Discover Weekly Engagement (%)',
    'Repeat Song Rate (%)'
]].mean()

print(subscription_behavior)


fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(14, 10))
fig.suptitle('Comparison of Streaming Behavior: Free vs. Premium Users', fontsize=16)

sns.barplot(x=subscription_behavior.index, y='Minutes Streamed Per Day', data=subscription_behavior, ax=axes[0, 0])
axes[0, 0].set_title('Average Minutes Streamed Per Day')
axes[0, 0].set_ylabel('Minutes Streamed')

sns.barplot(x=subscription_behavior.index, y='Number of Songs Liked', data=subscription_behavior, ax=axes[0, 1])
axes[0, 1].set_title('Average Number of Songs Liked')
axes[0, 1].set_ylabel('Songs Liked')

sns.barplot(x=subscription_behavior.index, y='Discover Weekly Engagement (%)', data=subscription_behavior, ax=axes[1, 0])
axes[1, 0].set_title('Average Discover Weekly Engagement (%)')
axes[1, 0].set_ylabel('Engagement (%)')

sns.barplot(x=subscription_behavior.index, y='Repeat Song Rate (%)', data=subscription_behavior, ax=axes[1, 1])
axes[1, 1].set_title('Average Repeat Song Rate (%)')
axes[1, 1].set_ylabel('Repeat Rate (%)')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

#there is no significant difference between the free and premium users on the basis of Average
#discover weekly engagement and others.



listening_time_counts = df['Listening Time (Morning/Afternoon/Night)'].value_counts()

plt.figure(figsize=(8, 6))
sns.barplot(x=listening_time_counts.index, y=listening_time_counts.values)
plt.title('Most Popular Listening Times')
plt.xlabel('Time of Day')
plt.ylabel('Number of Users')
plt.show()

print("Most popular listening times:")
print(listening_time_counts)

#During night users stream music the most

"""6. :Are there any regional trends in music streaming preferences?


"""

df.groupby(["Country","Top Genre"])["User_ID"].count()

age_Country= pd.crosstab(df["Country"],df["Top Genre"])
fig, ax= plt.subplots(figsize=(10,10))
age_Country.plot(kind='bar', ax = ax)
ax.set_xlabel("Country")
ax.set_ylabel("Frequency")
ax.set_title("Impact of Country on music preferences")

plt.show()

# Yes, regional trends affect music preferences by not significantly

